name: CI

on: 
    pull_request:
        branches:
        - main

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js 18
              uses: actions/setup-node@v4
              with:
                node-version: "18"

            - name: Install dependencies
              run: |
                cd ./src/payment
                npm ci

            - name: Test
              run: |
                cd ./src/payment
                npm test

    Code-Quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js 18
              uses: actions/setup-node@v4
              with:
                node-version: "18"
                
            - name: Install dependencies
              run: |
                cd ./src/payment
                npm ci

            - name: ESLint
              run: |
                cd ./src/payment
                npx eslint . --ext .js

    Docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: ./src/payment/
                file: ./src/payment/Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/payment:${{ github.run_id }}

    updatek8s:
        runs-on: ubuntu-latest
        needs: Docker

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.MY_ACTIONS_TOKEN }}

            - name: Update tag in kubernetes deployment manifest
              run: |
                sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/payment:${{github.run_id}}|" kubernetes/payment/deploy.yaml

            - name: Commit and Push Changes
              run: |
                git config --global user.email "fetuyee@gmail.com"
                git config --global user.name "iamfet"
                git add kubernetes/payment/deploy.yaml
                git commit -m "[CI]: Update payment image tag"
                git push origin HEAD:main -f